GET http://localhost:3000/posts
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyIjoiSmltIiwiaWF0IjoxNjg1ODA5NjAyLCJleHAiOjE2ODU4MDk2MTd9.hmSxnT9XP2fsRV4VCAz3WTNxzdk4eGeD5dSJRGZE3hY


###
POST http://localhost:3000/register
Content-Type: application/json

{
    "userName": "Jim",
    "email": "ImJim93@gmail.com",
    "password": "ImJim12345"
}


###
POST http://localhost:3000/token
Content-Type: application/json

{
    "token" : "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYW1lIjoiSmltIiwiaWF0IjoxNjg1ODA5NTc2LCJleHAiOjE2ODU4MDk2MzZ9.In9SX6lMb-aQvf-KHLggHAWJYPCKcOX88dxqIG91b7o"
}



###
POST http://localhost:3000/login
Content-Type: application/json

{
    "userName": "Jim",
    "email": "ImJim93@gmail.com",
    "password": "ImJim12345"
}